from .core import *
from .category_routes import *
from .menu_routes import *
from .fast_access_routes import *
from .partners import *
from .questions import *
from .readers import *
from .new_arrivals import *
from .contacts import *
from .work_hours import *
