version: "3.7"
services:
  web:
    build: web
    restart: always
    environment:
      - DEBUG=1
    networks:
      - flask_network
    depends_on:
      - db
    entrypoint: /code/entrypoint.sh

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network

  db:
    image: postgres:13
    restart: always
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=library
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  flask_network:

volumes:
  postgres_data: