"""empty message

Revision ID: 203199bea0fb
Revises: 
Create Date: 2021-07-28 17:19:03.457980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203199bea0fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_books', sa.Column('description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_books', 'description')
    # ### end Alembic commands ###
