"""empty message

Revision ID: 4d0f0a24c1ab
Revises: fb5a16e84e26
Create Date: 2021-05-12 11:35:10.915621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0f0a24c1ab'
down_revision = 'fb5a16e84e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'image')
    # ### end Alembic commands ###
