"""empty message

Revision ID: 6e7c6a7dcc40
Revises: 0b839e4ad97b
Create Date: 2021-04-30 21:51:52.294346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7c6a7dcc40'
down_revision = '0b839e4ad97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dtypesrecords')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'disptype_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('disptype_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'records', 'dtypesrecords', ['disptype_id'], ['id'])
    op.create_table('dtypesrecords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
