"""empty message

Revision ID: 7b737fb6d18c
Revises: 411b2d658f44
Create Date: 2021-05-09 14:32:40.135603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b737fb6d18c'
down_revision = '411b2d658f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('image', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'image')
    # ### end Alembic commands ###
