"""empty message

Revision ID: d36b61e26a3b
Revises: c93910dc2d3e
Create Date: 2021-07-31 17:11:58.844263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36b61e26a3b'
down_revision = 'c93910dc2d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('text_en', sa.String(length=300), nullable=True),
    sa.Column('text_kz', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_hours')
    # ### end Alembic commands ###
