"""empty message

Revision ID: eafd63dcc20c
Revises: 7b737fb6d18c
Create Date: 2021-05-09 14:57:25.841138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafd63dcc20c'
down_revision = '7b737fb6d18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('url', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'url')
    # ### end Alembic commands ###
