"""empty message

Revision ID: 5040adb9dde7
Revises: d36b61e26a3b
Create Date: 2021-08-01 16:05:49.110398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5040adb9dde7'
down_revision = 'd36b61e26a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_books', sa.Column('description_en', sa.TEXT(), nullable=True))
    op.add_column('new_books', sa.Column('description_kz', sa.TEXT(), nullable=True))
    op.add_column('new_books', sa.Column('text_en', sa.TEXT(), nullable=True))
    op.add_column('new_books', sa.Column('text_kz', sa.TEXT(), nullable=True))
    op.add_column('new_books', sa.Column('title_en', sa.String(length=250), nullable=True))
    op.add_column('new_books', sa.Column('title_kz', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_books', 'title_kz')
    op.drop_column('new_books', 'title_en')
    op.drop_column('new_books', 'text_kz')
    op.drop_column('new_books', 'text_en')
    op.drop_column('new_books', 'description_kz')
    op.drop_column('new_books', 'description_en')
    # ### end Alembic commands ###
