"""empty message

Revision ID: c93910dc2d3e
Revises: 8897326f391d
Create Date: 2021-07-29 17:24:38.017462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93910dc2d3e'
down_revision = '8897326f391d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('address_en', sa.String(length=300), nullable=True))
    op.add_column('contacts', sa.Column('address_kz', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'address_kz')
    op.drop_column('contacts', 'address_en')
    # ### end Alembic commands ###
